version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "typescript"
        versions:
          - "5.x"